// Code generated by mockery v2.3.0. DO NOT EDIT.

package vslack

import mock "github.com/stretchr/testify/mock"

// MockMarkdownOption is an autogenerated mock type for the MarkdownOption type
type MockMarkdownOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: m
func (_m *MockMarkdownOption) Execute(m *MarkdownConfiguration) {
	_m.Called(m)
}
